server:
  port: 8440
spring:
  application:
    name: trade-service
  datasource:
    url: jdbc:mysql://localhost/learning?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 999888
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 47.118.80.158:8848
mybatis:
  mapper-locations: classpath:mapper/*.xml
alipay:
  protocol: https
  gatewayHost:
  appId:
  signType: RSA2
  merchantPrivateKey:
  alipayPublicKey:
gateway:
  protocol: http
  host: 127.0.0.1:8080